CREATE TABLE IF NOT EXISTS `music_subgenres` (
    `genre` varchar(50) NOT NULL,
    `
subgenre` varchar(50) NOT NULL,
    KEY `genre` (`genre`))
    ENGINE=InnoDB
    DEFAULT CHARSET=latin1;

insert into music_subgenres values ('Alternative', 'Alternative Rock');
insert into music_subgenres values ('Alternative', 'Art Punk');
insert into music_subgenres values ('Alternative', 'College Rock');
insert into music_subgenres values ('Alternative', 'Crossover Thrash');
insert into music_subgenres values ('Alternative', 'Crust Punk');
insert into music_subgenres values ('Alternative', 'Experimental Rock');
insert into music_subgenres values ('Alternative', 'Folk Punk');
insert into music_subgenres values ('Alternative', 'Goth / Gothic Rock');
insert into music_subgenres values ('Alternative', 'Grunge');
insert into music_subgenres values ('Alternative', 'Hard Rock');
insert into music_subgenres values ('Alternative', 'Hardcore Punk');
insert into music_subgenres values ('Alternative', 'Indie Rock');
insert into music_subgenres values ('Alternative', 'Lo-fi');
insert into music_subgenres values ('Alternative', 'New Wave');
insert into music_subgenres values ('Alternative', 'Progressive Rock');
insert into music_subgenres values ('Alternative', 'Punk');
insert into music_subgenres values ('Alternative', 'Shoegaze');
insert into music_subgenres values ('Alternative', 'Steampunk');
insert into music_subgenres values ('Blues', 'Acoustic Blues');
insert into music_subgenres values ('Blues', 'Chicago Blues');
insert into music_subgenres values ('Blues', 'Classic Blues');
insert into music_subgenres values ('Blues', 'Contemporary Blues');
insert into music_subgenres values ('Blues', 'Country Blues');
insert into music_subgenres values ('Blues', 'Delta Blues');
insert into music_subgenres values ('Blues', 'Electric Blues');
insert into music_subgenres values ('Blues', 'Ragtime Blues');
insert into music_subgenres values ('Children’s Music', 'Lullabies');
insert into music_subgenres values ('Children’s Music', 'Sing-Along');
insert into music_subgenres values ('Children’s Music', 'Stories');
insert into music_subgenres values ('Christian & Gospel', 'CCM');
insert into music_subgenres values ('Christian & Gospel', 'Christian & Gospel');
insert into music_subgenres values ('Christian & Gospel', 'Christian Metal');
insert into music_subgenres values ('Christian & Gospel', 'Christian Pop');
insert into music_subgenres values ('Christian & Gospel', 'Christian Rap');
insert into music_subgenres values ('Christian & Gospel', 'Christian Rock');
insert into music_subgenres values ('Christian & Gospel', 'Classic Christian');
insert into music_subgenres values ('Christian & Gospel', 'Contemporary Gospel');
insert into music_subgenres values ('Christian & Gospel', 'Gospel');
insert into music_subgenres values ('Christian & Gospel', 'Praise & Worship');
insert into music_subgenres values ('Christian & Gospel', 'Qawwali');
insert into music_subgenres values ('Christian & Gospel', 'Southern Gospel');
insert into music_subgenres values ('Christian & Gospel', 'Traditional Gospel');
insert into music_subgenres values ('Classical', 'Avant-Garde');
insert into music_subgenres values ('Classical', 'Baroque');
insert into music_subgenres values ('Classical', 'Chamber Music');
insert into music_subgenres values ('Classical', 'Chant');
insert into music_subgenres values ('Classical', 'Choral');
insert into music_subgenres values ('Classical', 'Classical Crossover');
insert into music_subgenres values ('Classical', 'Contemporary Classical');
insert into music_subgenres values ('Classical', 'Early Music');
insert into music_subgenres values ('Classical', 'Expressionist');
insert into music_subgenres values ('Classical', 'High Classical');
insert into music_subgenres values ('Classical', 'Impressionist');
insert into music_subgenres values ('Classical', 'Medieval');
insert into music_subgenres values ('Classical', 'Minimalism');
insert into music_subgenres values ('Classical', 'Modern Composition');
insert into music_subgenres values ('Classical', 'Opera');
insert into music_subgenres values ('Classical', 'Orchestral');
insert into music_subgenres values ('Classical', 'Renaissance');
insert into music_subgenres values ('Classical', 'Romantic');
insert into music_subgenres values ('Classical', 'Wedding Music');
insert into music_subgenres values ('Comedy', 'Novelty');
insert into music_subgenres values ('Comedy', 'Standup Comedy');
insert into music_subgenres values ('Comedy', 'Vaudeville');
insert into music_subgenres values ('Commercial', 'Jingles');
insert into music_subgenres values ('Commercial', 'TV Themes');
insert into music_subgenres values ('Country', 'Alternative Country');
insert into music_subgenres values ('Country', 'Americana');
insert into music_subgenres values ('Country', 'Bluegrass');
insert into music_subgenres values ('Country', 'Contemporary Bluegrass');
insert into music_subgenres values ('Country', 'Contemporary Country');
insert into music_subgenres values ('Country', 'Country Gospel');
insert into music_subgenres values ('Country', 'Country Pop');
insert into music_subgenres values ('Country', 'Honky Tonk');
insert into music_subgenres values ('Country', 'Outlaw Country');
insert into music_subgenres values ('Country', 'Traditional Bluegrass');
insert into music_subgenres values ('Country', 'Traditional Country');
insert into music_subgenres values ('Country', 'Urban Cowboy');
insert into music_subgenres values ('Dance', 'Breakbeat / Breakstep');
insert into music_subgenres values ('Dance', 'Breakcore');
insert into music_subgenres values ('Dance', 'Brostep');
insert into music_subgenres values ('Dance', 'Chillstep');
insert into music_subgenres values ('Dance', 'Club / Club Dance');
insert into music_subgenres values ('Dance', 'Deep House');
insert into music_subgenres values ('Dance', 'Dubstep');
insert into music_subgenres values ('Dance', 'Electro House');
insert into music_subgenres values ('Dance', 'Electroswing');
insert into music_subgenres values ('Dance', 'Exercise');
insert into music_subgenres values ('Dance', 'Future Garage');
insert into music_subgenres values ('Dance', 'Garage');
insert into music_subgenres values ('Dance', 'Glitch Hop');
insert into music_subgenres values ('Dance', 'Glitch Pop');
insert into music_subgenres values ('Dance', 'Grime');
insert into music_subgenres values ('Dance', 'Hard Dance');
insert into music_subgenres values ('Dance', 'Hardcore');
insert into music_subgenres values ('Dance', 'Hi-NRG / Eurodance');
insert into music_subgenres values ('Dance', 'Horrorcore');
insert into music_subgenres values ('Dance', 'House');
insert into music_subgenres values ('Dance', 'Jackin House');
insert into music_subgenres values ('Dance', 'Jungle / Drum’n’bass');
insert into music_subgenres values ('Dance', 'Liquid Du');
insert into music_subgenres values ('Dance', 'Regstep');
insert into music_subgenres values ('Dance', 'Speedcore');
insert into music_subgenres values ('Dance', 'Techno');
insert into music_subgenres values ('Dance', 'Trance');
insert into music_subgenres values ('Dance', 'Trap');
insert into music_subgenres values ('Easy Listening', 'Bop');
insert into music_subgenres values ('Easy Listening', 'Lounge');
insert into music_subgenres values ('Easy Listening', 'Swing');
insert into music_subgenres values ('Electronic', '2-Step');
insert into music_subgenres values ('Electronic', 'Ambient');
insert into music_subgenres values ('Electronic', 'Bassline');
insert into music_subgenres values ('Electronic', 'Chillwav');
insert into music_subgenres values ('Electronic', 'Chiptune');
insert into music_subgenres values ('Electronic', 'Crunk');
insert into music_subgenres values ('Electronic', 'Downtempo');
insert into music_subgenres values ('Electronic', 'Drum & Bass');
insert into music_subgenres values ('Electronic', 'Electro');
insert into music_subgenres values ('Electronic', 'Electronic Rock');
insert into music_subgenres values ('Electronic', 'Electronica');
insert into music_subgenres values ('Electronic', 'Electro-swing');
insert into music_subgenres values ('Electronic', 'Hardstyle');
insert into music_subgenres values ('Electronic', 'IDM/Experimental');
insert into music_subgenres values ('Electronic', 'Industrial');
insert into music_subgenres values ('Electronic', 'Trip Hop');
insert into music_subgenres values ('Hip-Hop/Rap', 'Alternative Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'Bounce');
insert into music_subgenres values ('Hip-Hop/Rap', 'Dirty South');
insert into music_subgenres values ('Hip-Hop/Rap', 'East Coast Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'Gangsta Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'Hardcore Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'Hip-Hop');
insert into music_subgenres values ('Hip-Hop/Rap', 'Latin Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'Old School Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'Turntablism');
insert into music_subgenres values ('Hip-Hop/Rap', 'Underground Rap');
insert into music_subgenres values ('Hip-Hop/Rap', 'West Coast Rap');
insert into music_subgenres values ('Holiday', 'Chanukah');
insert into music_subgenres values ('Holiday', 'Christmas');
insert into music_subgenres values ('Holiday', 'Christmas: Children’s');
insert into music_subgenres values ('Holiday', 'Christmas: Classic');
insert into music_subgenres values ('Holiday', 'Christmas: Classical');
insert into music_subgenres values ('Holiday', 'Christmas: Comedy');
insert into music_subgenres values ('Holiday', 'Christmas: Jazz');
insert into music_subgenres values ('Holiday', 'Christmas: Modern');
insert into music_subgenres values ('Holiday', 'Christmas: Pop');
insert into music_subgenres values ('Holiday', 'Christmas: R&B');
insert into music_subgenres values ('Holiday', 'Christmas: Religious');
insert into music_subgenres values ('Holiday', 'Christmas: Rock');
insert into music_subgenres values ('Holiday', 'Easter');
insert into music_subgenres values ('Holiday', 'Halloween');
insert into music_subgenres values ('Holiday', 'Holiday: Other');
insert into music_subgenres values ('Holiday', 'Thanksgiving');
insert into music_subgenres values ('Instrumental', 'March');
insert into music_subgenres values ('Jazz', 'Acid Jazz');
insert into music_subgenres values ('Jazz', 'Avant-Garde Jazz');
insert into music_subgenres values ('Jazz', 'Bebop');
insert into music_subgenres values ('Jazz', 'Big Band');
insert into music_subgenres values ('Jazz', 'Blue Note');
insert into music_subgenres values ('Jazz', 'Contemporary Jazz');
insert into music_subgenres values ('Jazz', 'Cool');
insert into music_subgenres values ('Jazz', 'Crossover Jazz');
insert into music_subgenres values ('Jazz', 'Dixieland');
insert into music_subgenres values ('Jazz', 'Ethio-jazz');
insert into music_subgenres values ('Jazz', 'Fusion');
insert into music_subgenres values ('Jazz', 'Gypsy Jazz');
insert into music_subgenres values ('Jazz', 'Hard Bop');
insert into music_subgenres values ('Jazz', 'Latin Jazz');
insert into music_subgenres values ('Jazz', 'Mainstream Jazz');
insert into music_subgenres values ('Jazz', 'Ragtime');
insert into music_subgenres values ('Jazz', 'Smooth Jazz');
insert into music_subgenres values ('Jazz', 'Trad Jazz');
insert into music_subgenres values ('J-Pop', 'J-Punk');
insert into music_subgenres values ('J-Pop', 'J-Rock');
insert into music_subgenres values ('J-Pop', 'J-Ska');
insert into music_subgenres values ('J-Pop', 'J-Synth');
insert into music_subgenres values ('Latin', 'Alternativo & Rock Latino');
insert into music_subgenres values ('Latin', 'Argentine tango');
insert into music_subgenres values ('Latin', 'Baladas y Boleros');
insert into music_subgenres values ('Latin', 'Bossa Nova');
insert into music_subgenres values ('Latin', 'Brazilian');
insert into music_subgenres values ('Latin', 'Contemporary Latin');
insert into music_subgenres values ('Latin', 'Cumbia');
insert into music_subgenres values ('Latin', 'Flamenco / Spanish Flamenco');
insert into music_subgenres values ('Latin', 'Latin Jazz');
insert into music_subgenres values ('Latin', 'Nuevo Flamenco');
insert into music_subgenres values ('Latin', 'Pop Latino');
insert into music_subgenres values ('Latin', 'Portuguese fado');
insert into music_subgenres values ('Latin', 'Raíces');
insert into music_subgenres values ('Latin', 'Reggaeton y Hip-Hop');
insert into music_subgenres values ('Latin', 'Regional Mexicano');
insert into music_subgenres values ('Latin', 'Salsa y Tropical');
insert into music_subgenres values ('New Age', 'Environmental');
insert into music_subgenres values ('New Age', 'Healing');
insert into music_subgenres values ('New Age', 'Meditation');
insert into music_subgenres values ('New Age', 'Nature');
insert into music_subgenres values ('New Age', 'Relaxation');
insert into music_subgenres values ('New Age', 'Travel');
insert into music_subgenres values ('Pop', 'Adult Contemporary');
insert into music_subgenres values ('Pop', 'Britpop');
insert into music_subgenres values ('Pop', 'Bubblegum Pop');
insert into music_subgenres values ('Pop', 'Chamber Pop');
insert into music_subgenres values ('Pop', 'Dance Pop');
insert into music_subgenres values ('Pop', 'Dream Pop');
insert into music_subgenres values ('Pop', 'Electro Pop');
insert into music_subgenres values ('Pop', 'Orchestral Pop');
insert into music_subgenres values ('Pop', 'Pop Punk');
insert into music_subgenres values ('Pop', 'Pop/Rock');
insert into music_subgenres values ('Pop', 'Power Pop');
insert into music_subgenres values ('Pop', 'Soft Rock');
insert into music_subgenres values ('Pop', 'Synthpop');
insert into music_subgenres values ('Pop', 'Teen Pop');
insert into music_subgenres values ('R&B/Soul', 'Contemporary R&B');
insert into music_subgenres values ('R&B/Soul', 'Disco');
insert into music_subgenres values ('R&B/Soul', 'Doo Wop');
insert into music_subgenres values ('R&B/Soul', 'Funk');
insert into music_subgenres values ('R&B/Soul', 'Modern Soul');
insert into music_subgenres values ('R&B/Soul', 'Motown');
insert into music_subgenres values ('R&B/Soul', 'Neo-Soul');
insert into music_subgenres values ('R&B/Soul', 'Northern Soul');
insert into music_subgenres values ('R&B/Soul', 'Psychedelic Soul');
insert into music_subgenres values ('R&B/Soul', 'Quiet Storm');
insert into music_subgenres values ('R&B/Soul', 'Soul');
insert into music_subgenres values ('R&B/Soul', 'Soul Blues');
insert into music_subgenres values ('R&B/Soul', 'Southern Soul');
insert into music_subgenres values ('Reggae', '2-Tone');
insert into music_subgenres values ('Reggae', 'Dancehall');
insert into music_subgenres values ('Reggae', 'Dub');
insert into music_subgenres values ('Reggae', 'Roots Reggae');
insert into music_subgenres values ('Reggae', 'Ska');
insert into music_subgenres values ('Rock', 'Acid Rock');
insert into music_subgenres values ('Rock', 'Adult Alternative');
insert into music_subgenres values ('Rock', 'Adult-Oriented Rock');
insert into music_subgenres values ('Rock', 'Afro Punk');
insert into music_subgenres values ('Rock', 'Alternative Rock');
insert into music_subgenres values ('Rock', 'American Trad Rock');
insert into music_subgenres values ('Rock', 'Anatolian Rock');
insert into music_subgenres values ('Rock', 'Arena Rock');
insert into music_subgenres values ('Rock', 'Art Rock');
insert into music_subgenres values ('Rock', 'Blues-Rock');
insert into music_subgenres values ('Rock', 'British Invasion');
insert into music_subgenres values ('Rock', 'Cock Rock');
insert into music_subgenres values ('Rock', 'Death Metal / Black Metal');
insert into music_subgenres values ('Rock', 'Doom Metal');
insert into music_subgenres values ('Rock', 'Glam Rock');
insert into music_subgenres values ('Rock', 'Gothic Metal');
insert into music_subgenres values ('Rock', 'Grind Core');
insert into music_subgenres values ('Rock', 'Hair Metal');
insert into music_subgenres values ('Rock', 'Hard Rock');
insert into music_subgenres values ('Rock', 'Jam Bands');
insert into music_subgenres values ('Rock', 'Math Metal');
insert into music_subgenres values ('Rock', 'Math Rock');
insert into music_subgenres values ('Rock', 'Metal');
insert into music_subgenres values ('Rock', 'Metal Core');
insert into music_subgenres values ('Rock', 'Noise Rock');
insert into music_subgenres values ('Rock', 'Post Punk');
insert into music_subgenres values ('Rock', 'Progressive Metal');
insert into music_subgenres values ('Rock', 'Prog-Rock/Art Rock');
insert into music_subgenres values ('Singer/Songwriter', 'Alternative Folk');
insert into music_subgenres values ('Singer/Songwriter', 'Contemporary Folk');
insert into music_subgenres values ('Singer/Songwriter', 'Contemporary Singer/Songwriter');
insert into music_subgenres values ('Singer/Songwriter', 'Folk-Rock');
insert into music_subgenres values ('Singer/Songwriter', 'Indie Folk');
insert into music_subgenres values ('Singer/Songwriter', 'Love Song');
insert into music_subgenres values ('Singer/Songwriter', 'New Acoustic');
insert into music_subgenres values ('Singer/Songwriter', 'Traditional Folk');
insert into music_subgenres values ('Soundtrack', 'Foreign Cinema');
insert into music_subgenres values ('Soundtrack', 'Movie Soundtrack');
insert into music_subgenres values ('Soundtrack', 'Musicals');
insert into music_subgenres values ('Soundtrack', 'Original Score');
insert into music_subgenres values ('Soundtrack', 'Soundtrack');
insert into music_subgenres values ('Soundtrack', 'TV Soundtrack');
insert into music_subgenres values ('Tex-Mex / Tejano', 'Chicano');
insert into music_subgenres values ('Tex-Mex / Tejano', 'Classic');
insert into music_subgenres values ('Tex-Mex / Tejano', 'Conjunto');
insert into music_subgenres values ('Tex-Mex / Tejano', 'Conjunto Progressive');
insert into music_subgenres values ('Tex-Mex / Tejano', 'New Mex');
insert into music_subgenres values ('Tex-Mex / Tejano', 'Tex-Mex');
insert into music_subgenres values ('Vocal', 'A cappella');
insert into music_subgenres values ('Vocal', 'Barbershop');
insert into music_subgenres values ('Vocal', 'Doo-wop');
insert into music_subgenres values ('Vocal', 'Gregorian Chant');
insert into music_subgenres values ('Vocal', 'Standards');
insert into music_subgenres values ('Vocal', 'Traditional Pop');
insert into music_subgenres values ('Vocal', 'Vocal Jazz');
insert into music_subgenres values ('Vocal', 'Vocal Pop');
insert into music_subgenres values ('World', 'Africa');
insert into music_subgenres values ('World', 'Afro-Beat');
insert into music_subgenres values ('World', 'Afro-Pop');
insert into music_subgenres values ('World', 'Asia');
insert into music_subgenres values ('World', 'Australia');
insert into music_subgenres values ('World', 'Cajun');
insert into music_subgenres values ('World', 'Calypso');
insert into music_subgenres values ('World', 'Caribbean');
insert into music_subgenres values ('World', 'Carnatic');
insert into music_subgenres values ('World', 'Celtic');
insert into music_subgenres values ('World', 'Celtic Folk');
insert into music_subgenres values ('World', 'Contemporary Celtic');
insert into music_subgenres values ('World', 'Coupé-décalé');
insert into music_subgenres values ('World', 'Dangdut');
insert into music_subgenres values ('World', 'Drinking Songs');
insert into music_subgenres values ('World', 'Drone');
insert into music_subgenres values ('World', 'Europe');
insert into music_subgenres values ('World', 'France');
insert into music_subgenres values ('World', 'Hawaii');
insert into music_subgenres values ('World', 'Hindustani');
insert into music_subgenres values ('World', 'Indian Ghazal');
insert into music_subgenres values ('World', 'Indian Pop');
insert into music_subgenres values ('World', 'Japan');
insert into music_subgenres values ('World', 'Japanese Pop');
insert into music_subgenres values ('World', 'Klezmer');
insert into music_subgenres values ('World', 'Mbalax');
insert into music_subgenres values ('World', 'Middle East');
insert into music_subgenres values ('World', 'North America');
